name: RADAR AGORA

on:
  workflow_dispatch:

  schedule:
    - cron: '0 7 * * *'
      timezone: "America/Sao_Paulo"

    - cron: '0 14 * * *'
      timezone: "America/Sao_Paulo"

    - cron: '0 20 * * *'
      timezone: "America/Sao_Paulo"

jobs:
  teste:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4
      - name: Testar Gemini
        run: |
          curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent" \
            -H "x-goog-api-key: $GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "contents": [
                {
                  "parts": [
                    {
                      "text": "Responda somente: RADAR AGORA conectado."
                    }
                  ]
                }
              ]
            }'
