name: RADAR AGORA

on:
  workflow_dispatch:

  schedule:
    - cron: '0 7 * * *'
      timezone: "America/Sao_Paulo"

    - cron: '0 14 * * *'
      timezone: "America/Sao_Paulo"

    - cron: '0 20 * * *'
      timezone: "America/Sao_Paulo"

jobs:
  teste:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4
      - name: Verificar arquivos
        run: |
          echo "=== DIRETÓRIO ATUAL ==="
          pwd
          echo "=== ARQUIVOS ==="
          ls -la
      - name: Ler configuração
        run: |
          echo "=== CONFIGURAÇÃO ==="
          cat config.json
          echo "=== REGRAS ==="
          cat regras.json
      - name: Analisar estrutura das notícias
        run: |
          curl -L -s "https://www.agenciabrasilia.df.gov.br/noticias" -o noticias.html

          echo "=== TAMANHO DA PÁGINA ==="
          wc -c noticias.html

          echo "=== ASSET PUBLISHER ==="
          grep -n -i "asset-publisher" noticias.html | head -n 20

          echo "=== TÍTULOS VISÍVEIS ==="
          grep -n -i -E "noticia|notícias" noticias.html | head -n 30
